#!/usr/bin/env bash

# --follow: for symlinks
# --hidden
selected_dir=$( fd -t d --follow --exclude '.*' \
    | fzf --height=60% --border --prompt="cd  : " )

if [ -n "$selected_dir" ]; then
    echo "SELECTED DIRECTRY: '$selected_dir'" >&2

    if [ -d "$selected_dir" ]; then
        printf 'cd %q\n' "$selected_dir"
        printf 'll'  # long-format-listing
    else
        echo "ERROR: '$selected_dir' IS NOT A VALID DIRECTORY" >&2
    fi
else
    echo "NO DIRECTORY SELECTED" >&2
fi
# https://www.nerdfonts.com/cheat-sheet -> 
