#!/usr/bin/env bash
# AC POWER STATUS BLOCK
AC_PATH="/sys/class/power_supply/AC/online"

#AC_PATH=$(find /sys/class/power_supply/ -name "online" \
#    -path "*/A[CD]*" 2>/dev/null | head -1)
#
#if [[ -z "$AC_PATH" ]]; then
#    echo "no ac"
#    exit 0
#fi

online=$(cat "$AC_PATH")

ICON=""
if [[ "$online" == "1" ]]; then
    echo "<span foreground='#8fbcbb' background='#2e3440' size='x-large'>${ICON}</span><span background='#8fbcbb'> <span foreground='#111D13' size='x-large' rise='1pt'> </span><span foreground='#111D13' size='medium' rise='3pt'> </span></span><span background='#8fbcbb' foreground='#2e3440' size='x-large'>${ICON}</span>"
else
    echo "<span foreground='#D00000' background='#2e3440' size='x-large'>${ICON}</span><span background='#D00000'><span foreground='#FEEFDD' size='large' rise='1pt'> UNPLUGGED</span> </span><span background='#D00000' foreground='#2e3440' size='x-large'>${ICON}</span>"
fi
