#!/usr/bin/env bash

IMG="${XDG_RUNTIME_DIR:-/tmp}/lockscreen_$(date +%H%M%S).png"
import -window root "$IMG"
i3lock -i "$IMG" \
    --ring-width=5 \
    --radius=70 \
    --noinput-text="" \
    --verif-text="" \
    --wrong-text=""
