#!/usr/bin/env bash

# Configuration
ORIGINAL_IMG="$HOME/Gallery/_wallpapers/b-392.jpg"
LOCK_IMG="${XDG_RUNTIME_DIR:-/tmp}/current_lock_screen.png"

if [[ ! -f "$LOCK_IMG" ]] || [[ "$ORIGINAL_IMG" -nt "$LOCK_IMG" ]]; then
    echo "Generating new lock image..."
    
    RES=$(xdpyinfo | awk '/dimensions/{print $2}')
    
    magick "$ORIGINAL_IMG" -filter Gaussian -resize "$RES^" -gravity center -extent "$RES" "$LOCK_IMG"
fi

i3lock -i "$LOCK_IMG" --nofork
