#!/usr/bin/env bash

i3lock \
    --blur 5 \
    --nofork \
    --ignore-empty-password \
    --screen 1 \
    \
    --bar-indicator \
    --bar-pos y+h \
    --bar-direction 1 \
    --bar-max-height 30 \
    --bar-base-width 30 \
    --bar-periodic-step 50 \
    --bar-step 50 \
    --bar-color 000000aa \
    --keyhl-color 689d6aff \
    --bshl-color fabd2fff \
    --redraw-thread \
    \
    --clock \
    --force-clock \
    --time-str="%H:%M:%S" \
    \
    --time-pos x+40:y+h-110 \
    --date-pos tx:ty+40 \
    --time-align 1 \
    --date-align 1 \
    \
    --time-size 70 \
    --date-size 34 \
    \
    --time-color eceff4ff \
    --date-color d8dee9ff \
    \
    --status-pos x+40:y+h-35 \
    --verif-align 1 \
    --wrong-align 1 \
    \
    --verif-color 689d6aff \
    --wrong-color cc241dff \
    \
    --verif-text="" \
    --wrong-text="X" \
    --noinput-text="" \
    \
    --modif-pos -50:-50
