#!/usr/bin/env bash

ATTACH_DIR="$HOME/Zettelkasten/attachments"
[[ ! -d "$ATTACH_DIR" ]] && mkdir -p "$ATTACH_DIR" && notify-send "Attachment folder created" "$ATTACH_DIR"

OUTPUT_FILE="shot_$(date +%y-%m-%d_%H-%M-%S).jpg"

import png:- | magick png:- -trim +repage -strip -quality 80 "$ATTACH_DIR/$OUTPUT_FILE"

notify-send "Screenshot saved" "$(basename "$OUTPUT_FILE")"

echo "[[$OUTPUT_FILE]]" | xclip -i -selection secondary
