#!/usr/bin/env bash
# if [[ -n "$BLOCK_BUTTON" && "$BLOCK_BUTTON" -eq 1 ]]; then
if [[ "$BLOCK_BUTTON" -eq 1 ]]; then
    pactl set-sink-mute @DEFAULT_SINK@ toggle
fi

case "$1" in
    up)
        pactl set-sink-volume @DEFAULT_SINK@ +5%
        ;;
    down)
        pactl set-sink-volume @DEFAULT_SINK@ -5%
        ;;
    toggle)
        pactl set-sink-mute @DEFAULT_SINK@ toggle
        ;;
esac

NUM=$(pactl get-sink-volume @DEFAULT_SINK@ | awk '{print $5; exit}')
MUTED=$(pactl get-sink-mute @DEFAULT_SINK@ | awk '{print $2}')

if [[ $MUTED == "yes" ]]; then
    echo "<span foreground='#D00000' background='#2e3440' size='x-large'></span><span background='#D00000' foreground='#FEEFDD'> <span size='x-large'> </span> <span size='large' rise='1pt'>$NUM</span> </span><span background='#D00000' foreground='#2e3440' size='x-large'></span>"
else
    echo "<span foreground='#8fbcbb' background='#2e3440' size='x-large'></span><span background='#8fbcbb'> <span size='x-large'> </span> <span size='large' rise='1pt'>$NUM</span> </span><span background='#8fbcbb' foreground='#2e3440' size='x-large'></span>"
fi

pkill -RTMIN+10 i3blocks