#!/usr/bin/env bash
#
# USE BLOCK_INSTANCE IF SET, OTHERWISE DEFAULT TO wlp3s0
device="${BLOCK_INSTANCE:-wlp3s0}"
if [[ $(cat /sys/class/net/$device/operstate) == "up" ]]; then  # DOESN’T GUARANTEE IT’S WIRELESS
    if [[ -d "/sys/class/net/${device}/wireless" ]]; then  
        # THIS TELLS YOU THE INTERFACE IS ACTUALLY A Wi-Fi INTERFACE
        quality=$(grep ${device} /proc/net/wireless | awk '{ print int($3 * 100 / 70) }')
        echo "<span rise='2pt' size='x-large'>󰤥 </span><span rise='3pt' size='large'>${quality}%</span>"
        if [[ "${quality}" -le 20 ]]; then
            exit 33
        fi
    else
        # ETHERNET
        echo "<span rise='2pt' size='x-large'>󰤥 </span><span rise='3pt' >UP</span>"
    fi
else
    echo "<span rise='2pt' size='x-large'>󰤥 </span><span rise='3pt'>DOWN</span>"
    exit 33
fi

